# Generated by Django 5.2 on 2025-05-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('mecaniciens', '0001_initial'),
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('etat', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('en_pause', 'En pause'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes_mecanicien', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reparations', to='clients.client')),
                ('mecanicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparations', to='mecaniciens.mecanicien')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparations', to='vehicules.vehicule')),
            ],
        ),
    ]
